#!/bin/sh /etc/rc.common

START=90
STOP=10

start() {
  chmod 755 /usr/subconverter/subconverter
  /usr/subconverter/subconverter &
}

stop() {
  killall subconverter 2>/dev/null
}

restart() {
  stop
  start
}
